// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortafolioProyectos.Context;

namespace JuegosOlimpicos.Migrations
{
    [DbContext(typeof(JuegosOlimpicosDbContext))]
    [Migration("20210109151617_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JuegosOlimpicos.Models.Deportista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Deportistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Carlos Alviz",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Andres Sabogal",
                            PaisId = 2
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Jorge Ortega",
                            PaisId = 3
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Pablo Velasco",
                            PaisId = 4
                        });
                });

            modelBuilder.Entity("JuegosOlimpicos.Models.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Paises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "AUS"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "CHN"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "FRA"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "ALE"
                        });
                });

            modelBuilder.Entity("JuegosOlimpicos.Models.Deportista", b =>
                {
                    b.HasOne("JuegosOlimpicos.Models.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
